name: Nightly scrape

on:
  schedule:
    - cron: '5 2 * * *'   # 02:05 UTC daily
  workflow_dispatch:

permissions:
  contents: write  # Required to push changes to the repository

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps & run scrapers
        run: |
          pip install -r requirements.txt
          python scrape.py

      - name: Commit & push if changed
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add data/grants.json data/scraper_status.json
          git diff --quiet && echo "No changes" || git commit -m 'Nightly scrape'
          git push